spring.application.name=transport-management-system
#server.port=8045
# MySQL Properties
#spring.datasource.url=jdbc:mysql://localhost:3306/transport_management_db?createDatabaseIfNotExist=true&useUnicode=true
spring.datasource.url=jdbc:mysql://localhost:3306/transport_management_db?createDatabaseIfNotExist=true&useUnicode=true
#spring.datasource.username=root
spring.datasource.username=thucnd
#enter the correct MySQL Password below
#spring.datasource.password=123456
spring.datasource.password=thucnd@1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

springdoc.packagesToScan=com.transportmanagement.controller
springdoc.pathsToMatch=/api/**

server.address=0.0.0.0
server.port=8080
# File upload properties
#com.transportmanagement.image.folder.path=D:/upload_hpfile/documents
#"/home/adminserver/upload_hpfile/documents/"
com.transportmanagement.image.folder.path="/home/adminserver/upload_hpfile/documents"
#invoice static data
com.transportmanagement.company.name=DNS Transport System
com.transportmanagement.company.address=7, Demo Street, Demo City, Demo State, Demo Pin: 123456
com.transportmanagement.company.email=example.dnstransport.com
com.transportmanagement.company.gstno=ABCDEFG0000H
com.transportmanagement.company.contactNo=+91 1234567890

com.transportmanagement.company.bank.name=HDFC Bank
com.transportmanagement.company.bank.branch=Pune
com.transportmanagement.company.bank.accountNo=000000000000
com.transportmanagement.company.bank.ifscCode=ABCD1234

com.transportmanagement.company.goods.packages=LOOSE
com.transportmanagement.company.goods.commodity=IMP STEAM COAL
com.transportmanagement.company.goods.beNo=123
com.transportmanagement.company.goods.cbm=ABC
com.transportmanagement.company.goods.gpNo=123
com.transportmanagement.company.goods.billNo=588
com.transportmanagement.company.goods.stNo=123
com.transportmanagement.company.goods.ewayBill=ABC
com.transportmanagement.company.goods.tpNo=123
com.transportmanagement.company.goods.billAmt=2,35,545.00
com.transportmanagement.company.goods.weight=1000 MT
com.transportmanagement.company.goods.freight=1000 MT


com.transportmanagement.company.amount.totalFreight=1,14,497.50
com.transportmanagement.company.amount.gauranteeCharges=800.00
com.transportmanagement.company.amount.bitlyCharges=100.00
com.transportmanagement.company.amount.advanceAmount=15,000.00
com.transportmanagement.company.amount.roundOff=0.50
com.transportmanagement.company.amount.freightToPay=1,00,398.00

com.transportmanagement.company.amount.advance=15,000.00
com.transportmanagement.company.invoice.notice=The Consignment covered by this set of special lorry receipt from shall be stored at the destination nder the control of the transport operator & shall be delivered to or the order of the consignee bank whose name is mentioned in the lorry receipt it will under no circumstances be delivered to any one without the written authority from the consignee bank or its order endorsed on sondignee copy in on selerate letter of authority.
com.transportmanagement.company.invoice.termsandconditionline1=The Consignment note issued Subject to condition Printed Overleaf
com.transportmanagement.company.invoice.termsandconditionline2=We are not responsible for Leakage and Brackage
com.transportmanagement.company.invoice.termsandconditionline3=Shortage Allowed 1%
com.transportmanagement.company.invoice.termsandconditionline4=Please issue in favour of us form No 16-A, as per Section 194-C of Income Tax act
